[target.aarch64-linux-android]
ar = "C:\\Android\\android-ndk-r29\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android-ar.exe"
linker = "C:\\Android\\android-ndk-r29\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android21-clang.cmd"

[target.armv7-linux-androideabi]
ar = "C:\\Android\\android-ndk-r29\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\arm-linux-androideabi-ar.exe"
linker = "C:\\Android\\android-ndk-r29\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\armv7a-linux-androideabi21-clang.cmd"
